/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcmruv;

/**
 *
 * @author codeli4m
 */
public class JFrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCalculadora
     */
    
    
    public boolean isDouble(String texto){
       boolean res = false;
        try {
            double n = Double.parseDouble(texto);
            res = true;
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
       return res;
    }
    
    private void startMessageEmpty(){
        jLabelError.setText("");
    }
    
    public JFrameCalculadora() {
        initComponents();
        startMessageEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextAreaResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        jLabelVariable = new javax.swing.JLabel();
        jTextFieldDistancia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Container1 = new javax.swing.JPanel();
        jLabelVariable1 = new javax.swing.JLabel();
        jTextFieldVelocInicial = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Container2 = new javax.swing.JPanel();
        jLabelVariable2 = new javax.swing.JLabel();
        jTextFieldVelocFinal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Container3 = new javax.swing.JPanel();
        jLabelVariable3 = new javax.swing.JLabel();
        jTextFieldTiempo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Container4 = new javax.swing.JPanel();
        jLabelVariable4 = new javax.swing.JLabel();
        jTextFieldAceleracion = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(237, 240, 243));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        jTextAreaResult.setBackground(java.awt.Color.white);
        jTextAreaResult.setColumns(20);
        jTextAreaResult.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jTextAreaResult.setForeground(new java.awt.Color(109, 109, 109));
        jTextAreaResult.setRows(5);
        jTextAreaResult.setText("Se esta calculando la variable:\n\tAceleracion\nEl resultado es:\n\tA = 24 m/s");
        jTextAreaResult.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));

        jLabel1.setBackground(new java.awt.Color(86, 92, 101));
        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(86, 92, 101));
        jLabel1.setText("Calculadora MRUV");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 103, 103));
        jLabel2.setText("Completa los datos que tengas, deja en blanco las variable a calcular");

        Container.setBackground(new java.awt.Color(237, 240, 243));
        Container.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabelVariable.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelVariable.setForeground(new java.awt.Color(79, 79, 79));
        jLabelVariable.setText("Distancia (d)");

        jTextFieldDistancia.setBackground(java.awt.Color.white);
        jTextFieldDistancia.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jTextFieldDistancia.setForeground(new java.awt.Color(109, 109, 109));
        jTextFieldDistancia.setToolTipText("");
        jTextFieldDistancia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 16, 2, 16)));
        jTextFieldDistancia.setCaretColor(java.awt.Color.darkGray);
        jTextFieldDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDistanciaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jLabel4.setBackground(new java.awt.Color(180, 180, 180));
        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(58, 65, 75));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("m");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariable)
                    .addComponent(jTextFieldDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Container1.setBackground(new java.awt.Color(237, 240, 243));
        Container1.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabelVariable1.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelVariable1.setForeground(new java.awt.Color(79, 79, 79));
        jLabelVariable1.setText("Velocidad Inicial (Vo)");

        jTextFieldVelocInicial.setBackground(java.awt.Color.white);
        jTextFieldVelocInicial.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jTextFieldVelocInicial.setForeground(new java.awt.Color(109, 109, 109));
        jTextFieldVelocInicial.setToolTipText("");
        jTextFieldVelocInicial.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 16, 2, 16)));
        jTextFieldVelocInicial.setCaretColor(java.awt.Color.darkGray);
        jTextFieldVelocInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVelocInicialActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));

        jLabel5.setBackground(new java.awt.Color(180, 180, 180));
        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 65, 75));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("m/s");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Container1Layout = new javax.swing.GroupLayout(Container1);
        Container1.setLayout(Container1Layout);
        Container1Layout.setHorizontalGroup(
            Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariable1)
                    .addComponent(jTextFieldVelocInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Container1Layout.setVerticalGroup(
            Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVelocInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Container2.setBackground(new java.awt.Color(237, 240, 243));
        Container2.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabelVariable2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelVariable2.setForeground(new java.awt.Color(79, 79, 79));
        jLabelVariable2.setText("Velocidad Final (Vf)");

        jTextFieldVelocFinal.setBackground(java.awt.Color.white);
        jTextFieldVelocFinal.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jTextFieldVelocFinal.setForeground(new java.awt.Color(109, 109, 109));
        jTextFieldVelocFinal.setToolTipText("");
        jTextFieldVelocFinal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 16, 2, 16)));
        jTextFieldVelocFinal.setCaretColor(java.awt.Color.darkGray);
        jTextFieldVelocFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVelocFinalActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(220, 220, 220));

        jLabel6.setBackground(new java.awt.Color(180, 180, 180));
        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(58, 65, 75));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("m/s");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Container2Layout = new javax.swing.GroupLayout(Container2);
        Container2.setLayout(Container2Layout);
        Container2Layout.setHorizontalGroup(
            Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariable2)
                    .addComponent(jTextFieldVelocFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Container2Layout.setVerticalGroup(
            Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVelocFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Container3.setBackground(new java.awt.Color(237, 240, 243));
        Container3.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabelVariable3.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelVariable3.setForeground(new java.awt.Color(79, 79, 79));
        jLabelVariable3.setText("Tiempo (t)");

        jTextFieldTiempo.setBackground(java.awt.Color.white);
        jTextFieldTiempo.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jTextFieldTiempo.setForeground(new java.awt.Color(109, 109, 109));
        jTextFieldTiempo.setToolTipText("");
        jTextFieldTiempo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 16, 2, 16)));
        jTextFieldTiempo.setCaretColor(java.awt.Color.darkGray);
        jTextFieldTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(220, 220, 220));

        jLabel7.setBackground(new java.awt.Color(180, 180, 180));
        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 65, 75));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("seg");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Container3Layout = new javax.swing.GroupLayout(Container3);
        Container3.setLayout(Container3Layout);
        Container3Layout.setHorizontalGroup(
            Container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariable3)
                    .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Container3Layout.setVerticalGroup(
            Container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Container4.setBackground(new java.awt.Color(237, 240, 243));
        Container4.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabelVariable4.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelVariable4.setForeground(new java.awt.Color(79, 79, 79));
        jLabelVariable4.setText("Aceleracion (a)");

        jTextFieldAceleracion.setBackground(java.awt.Color.white);
        jTextFieldAceleracion.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jTextFieldAceleracion.setForeground(new java.awt.Color(109, 109, 109));
        jTextFieldAceleracion.setToolTipText("");
        jTextFieldAceleracion.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 16, 2, 16)));
        jTextFieldAceleracion.setCaretColor(java.awt.Color.darkGray);
        jTextFieldAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAceleracionActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(220, 220, 220));

        jLabel8.setBackground(new java.awt.Color(180, 180, 180));
        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 65, 75));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("m/s");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Container4Layout = new javax.swing.GroupLayout(Container4);
        Container4.setLayout(Container4Layout);
        Container4Layout.setHorizontalGroup(
            Container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariable4)
                    .addComponent(jTextFieldAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Container4Layout.setVerticalGroup(
            Container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCalcular.setBackground(new java.awt.Color(25, 135, 84));
        jButtonCalcular.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jButtonCalcular.setForeground(java.awt.Color.white);
        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 135, 84), 4, true));
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(220, 53, 69));
        jLabelError.setText("ERROR: Solo se aceptan numeros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Container4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Container3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabelError))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextAreaResult, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Container2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelError)))
                .addGap(18, 18, 18)
                .addComponent(jTextAreaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDistanciaActionPerformed

    private void jTextFieldVelocInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVelocInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVelocInicialActionPerformed

    private void jTextFieldVelocFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVelocFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVelocFinalActionPerformed

    private void jTextFieldTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoActionPerformed

    private void jTextFieldAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAceleracionActionPerformed

    private void showErrorForDoubles(){
        jLabelError.setText("ERROR: Solo se aceptan numeros");    
    }
    
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        MRUV mr = new MRUV();
//        while (true){
//        }
        boolean isError = false;
        if (!jTextFieldVelocInicial.getText().isEmpty()){
            if (isDouble(jTextFieldVelocInicial.getText())){
                mr.setVelocidadInicial(Double.parseDouble(jTextFieldVelocInicial.getText()));
            }
            else{
                showErrorForDoubles();
                isError = true;
            }
        }
        if (!jTextFieldVelocFinal.getText().isEmpty()){
            if (isDouble(jTextFieldVelocFinal.getText())){
                mr.setVelocidadFinal(Double.parseDouble(jTextFieldVelocFinal.getText()));
            }
            else{
                showErrorForDoubles();
                isError = true;
            }
        }
        if (!jTextFieldDistancia.getText().isEmpty()){
            if (isDouble(jTextFieldDistancia.getText())){
                mr.setDistancia(Double.parseDouble(jTextFieldDistancia.getText()));
            }
            else{
                showErrorForDoubles();
                isError = true;
            }
        }
        if (!jTextFieldTiempo.getText().isEmpty()){
            if (isDouble(jTextFieldTiempo.getText())){
                mr.setTiempo(Double.parseDouble(jTextFieldTiempo.getText()));
            }
            else{
                showErrorForDoubles();
                isError = true;
            }
        }
        if (!jTextFieldAceleracion.getText().isEmpty()){
            if (isDouble(jTextFieldAceleracion.getText())){
                mr.setAceleracion(Double.parseDouble(jTextFieldAceleracion.getText()));
            }
            else{
                showErrorForDoubles();
                isError = true;
            }
        }        
        
//        mr.setDistancia(60);
//        mr.setVelocidadInicial(10);
//        mr.setVelocidadFinal(50);
//        mr.setTiempo(2);
//        mr.setAceleracion(20);
    
        if (!isError){
            String response = mr.resolve();
            jTextAreaResult.setText(response);    
        }else{
            jTextAreaResult.setText("Soluciona los errores para ver resultados");                
        }

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Container1;
    private javax.swing.JPanel Container2;
    private javax.swing.JPanel Container3;
    private javax.swing.JPanel Container4;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelVariable;
    private javax.swing.JLabel jLabelVariable1;
    private javax.swing.JLabel jLabelVariable2;
    private javax.swing.JLabel jLabelVariable3;
    private javax.swing.JLabel jLabelVariable4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextArea jTextAreaResult;
    private javax.swing.JTextField jTextFieldAceleracion;
    private javax.swing.JTextField jTextFieldDistancia;
    private javax.swing.JTextField jTextFieldTiempo;
    private javax.swing.JTextField jTextFieldVelocFinal;
    private javax.swing.JTextField jTextFieldVelocInicial;
    // End of variables declaration//GEN-END:variables
}
